namespaces:
  - name: argocd
    extraLabels: {}
    extraAnnotations: {}
  - name: vault
    extraLabels: {}
    extraAnnotations: {}
  - name: keycloak
    extraLabels: {}
    extraAnnotations: {}
  - name: postgres
    extraLabels: {}
    extraAnnotations: {}
  - name: crossplane
    extraLabels: {}
    extraAnnotations: {}
