{{/*
Create a dedicated namespace per tenant in the management cluster.
This allows tenant Application resources to live in their own
namespace and avoids naming conflicts.
*/}}

apiVersion: v1
kind: Namespace
metadata:
  name: gitops-{{ .Values.tenant.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
{{ include "common.labels" . | nindent 4 }}
    platform.fluxdojo.local/tenant: "{{ .Values.tenant.name | lower }}"

---
