# This AppProject is used to deploy tenant components.
{{- if .Capabilities.APIVersions.Has "argoproj.io/v1alpha1/AppProject" }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant-system
spec:
  description: Project for tenant Argo CD resources.
  sourceRepos:
    - https://github.com/rezakaramad/micro-idp
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
    - group: argoproj.io
      kind: Application
    - group: argoproj.io
      kind: ApplicationSet
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: repo.github.upbound.io
      kind: Repository
    - group: repo.github.upbound.io
      kind: RepositoryFile
{{- end }}
