apiVersion: v2
name: external-secrets
description: External secrets management for Kubernetes
version: 0.0.1
dependencies:
  - name: external-secrets
    version: 2.0.0
    repository: https://charts.external-secrets.io/
