{{- if .Values.azureADProvider.enabled }}

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crossplane-admin
  namespace: crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  refreshInterval: 20m
  secretStoreRef:
    name: vault-local
    kind: ClusterSecretStore
  target:
    name: crossplane-admin
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      mergePolicy: Replace
      data:
        credentials: |
          {{ dict
              "tenantId" .tenant_id
              "clientId" .client_id
              "clientSecret" .client_secret
              "environment" "public"
            | toJson }}
  data:
    - secretKey: client_id
      remoteRef:
        key: management/azure/crossplane
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: management/azure/crossplane
        property: client_secret
    - secretKey: tenant_id
      remoteRef:
        key: management/azure/crossplane
        property: tenant_id

---
{{- end }}
