{{- if .Capabilities.APIVersions.Has "azuread.m.upbound.io/v1beta1/ProviderConfig" }}
{{- if .Values.azureADProvider.enabled }}

apiVersion: azuread.m.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: azuread
  namespace: crossplane
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane
      name: crossplane-admin
      key: credentials

{{- end }}
{{- end }}
