apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azure-oidc-management
  namespace: keycloak
spec:
  refreshInterval: 20m
  secretStoreRef:
    name: vault-local
    kind: ClusterSecretStore
  target:
    name: azure-oidc-management
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: local/management/keycloak/azure/apps/fluxdojo-keycloak-management-idp
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: local/management/keycloak/azure/apps/fluxdojo-keycloak-management-idp
        property: client_secret

---
