apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 20m
  secretStoreRef:
    name: vault-local
    kind: ClusterSecretStore
  target:
    name: keycloak-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: local/management/keycloak/admin
        property: username
    - secretKey: password
      remoteRef:
        key: local/management/keycloak/admin
        property: password
