apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-initial-admin
  namespace: keycloak
spec:
  refreshInterval: 20m
  secretStoreRef:
    name: vault-local
    kind: ClusterSecretStore
  target:
    name: keycloak-initial-admin
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: local/management/keycloak/initial-admin
        property: username
    - secretKey: password
      remoteRef:
        key: local/management/keycloak/initial-admin
        property: password
