apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-bootstrap
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 20m
  secretStoreRef:
    name: vault-local
    kind: ClusterSecretStore
  target:
    name: keycloak-bootstrap
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: local/management/keycloak/bootstrap
        property: username
    - secretKey: password
      remoteRef:
        key: local/management/keycloak/bootstrap
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-administrator
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 20m
  secretStoreRef:
    name: vault-local
    kind: ClusterSecretStore
  target:
    name: keycloak-administrator
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: local/management/keycloak/administrator
        property: username
    - secretKey: password
      remoteRef:
        key: local/management/keycloak/administrator
        property: password
