apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-keycloak
  namespace: keycloak
spec:
  instances: 1
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "768MB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1"

# apiVersion: acid.zalan.do/v1
# kind: postgresql
# metadata:
#   name: pg-keycloak
#   namespace: keycloak
#   annotations:
#     argocd.argoproj.io/sync-wave: "-5"
# spec:
#   teamId: "keycloak"
#   numberOfInstances: 1
#   postgresql:
#     version: "16"
#   volume:
#     size: 1Gi
#   users:
#     keycloak:
#       - createdb
#   databases:
#     keycloak: keycloak
#   enableMasterLoadBalancer: false
#   enableReplicaLoadBalancer: false
#   maintenanceWindows:
#     - "02:00-03:00"
