apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: pg-keycloak
  namespace: keycloak
spec:
  teamId: "keycloak"
  numberOfInstances: 1
  postgresql:
    version: "16"
  volume:
    size: 1Gi
  users:
    keycloak:
      - createdb
  databases:
    keycloak: keycloak
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  maintenanceWindows:
    - "02:00-03:00"
