apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  name: realm-management
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  managementPolicies: ["Observe"]
  forProvider:
    clientId: realm-management
    realmId: management
  providerConfigRef:
    kind: ProviderConfig
    name: keycloak

---
