apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-rezakaramad
  namespace: argocd
spec:
  refreshInterval: 20m
  secretStoreRef:
    name: vault-local
    kind: ClusterSecretStore
  target:
    name: github-app-rezakaramad
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: https://github.com/rezakaramad
      mergePolicy: Merge
  data:
    - secretKey: githubAppID
      remoteRef:
        key: management/github/apps/argocd
        property: app-id

    - secretKey: githubAppInstallationID
      remoteRef:
        key: management/github/apps/argocd
        property: installation-id

    - secretKey: githubAppPrivateKey
      remoteRef:
        key: management/github/apps/argocd
        property: private-key

---
