namespaces:
  - name: platform-resources
    extraLabels: {}
    extraAnnotations: {}
  - name: argocd
    extraLabels: {}
    extraAnnotations: {}
  - name: vault
    extraLabels: {}
    extraAnnotations: {}
  - name: keycloak-system
    extraLabels: {}
    extraAnnotations: {}
  - name: postgres-system
    extraLabels: {}
    extraAnnotations: {}
