{{- if .Capabilities.APIVersions.Has "pkg.crossplane.io/v1/Provider" }}
{{- if .Values.azureADProvider.enabled }}

apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azuread
spec:
  package: {{ .Values.azureADProvider.providerPackage }}

{{- end }}
{{- end }}
