apiVersion: v2
name: crossplane
description: Crossplane enables platform teams to manage infrastructure from multiple vendors, and expose higher level self-service APIs for application teams to consume.
type: application
version: 0.0.1
dependencies:
  - name: crossplane
    version: 2.1.3
    repository: https://charts.crossplane.io/stable
