githubProvider:
  enabled: false
  providerPackage: xpkg.upbound.io/crossplane-contrib/provider-upjet-github:v0.18.7

keycloakProvider:
  enabled: true
  providerPackage: xpkg.upbound.io/crossplane-contrib/provider-keycloak:v0.12.0


