apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
  namespace: platform-system
spec:
  isCA: true
  commonName: root-ca
  secretName: root-ca-secret
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always
