apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-mgmt
  namespace: argocd
spec:
  project: platform-system
  source:
    repoURL: https://github.com/rezakaramad/micro-idp
    targetRevision: HEAD
    path: charts/traefik
  destination:
    name: in-cluster
    namespace: platform-resources
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
