{{- if .Capabilities.APIVersions.Has "pkg.crossplane.io/v1/Function" }}
{{- if .Values.tenantBootstrap.enabled }}

apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: crossplane-contrib-function-go-templating
spec:
  package: {{ .Values.tenantBootstrap.functions.goTemplating.providerPackage }}

---
{{- end }}
{{- end }}
