{{- if .Capabilities.APIVersions.Has "cert-manager.io/v1/ClusterIssuer" }}

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root-ca
spec:
  ca:
    secretName: root-ca-secret

{{- end }}
