{{- if .Values.keycloakProvider.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-master
  namespace: crossplane
spec:
  refreshInterval: 20m
  secretStoreRef:
    name: vault-local
    kind: ClusterSecretStore
  target:
    name: keycloak-master
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      mergePolicy: Replace
      data:
        credentials: |
          {
            "client_id": "{{`{{ .client_id }}`}}",
            "client_secret": "{{`{{ .client_secret }}`}}",
            "url": "{{ .Values.keycloakProvider.keycloakUrl }}",
            "realm": "master"
          }
  data:
    - secretKey: client_id
      remoteRef:
        key: management/keycloak/crossplane
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: management/keycloak/crossplane
        property: client_secret
{{- end }}
